// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";

function fib(x) {
  if (x === 0 || x === 1) {
    return x;
  } else {
    return fib(x - 1 | 0) + fib(x - 2 | 0) | 0;
  }
}

var res = fib(16);

console.log(String(res));

var x$prime = List.map((function (i) {
        return i + 1 | 0;
      }), /* :: */[
      1,
      /* :: */[
        2,
        /* :: */[
          3,
          /* [] */0
        ]
      ]
    ]);

List.iter((function (i) {
        console.log(String(i));
        return /* () */0;
      }), x$prime);

export {
  fib ,
  
}
/* res Not a pure module */
